Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,24 +31,37 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     steps:
+      # Create the private key file from the GitHub Secrets
       - name: Create Private Key for SSH
         run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > cinepass-server
 
+      # Set proper permissions for the private key file
       - name: Set Permissions for Private Key
         run: chmod 600 cinepass-server
 
+      # Deploy to DigitalOcean droplet via SSH
       - name: Deploy to DigitalOcean droplet via SSH
         uses: appleboy/ssh-action@master
         with:
-          host: ${{ secrets.DIGITAL_IP4_ADDRESS }}
-          username: root
-          key: cinepass-server
-          passphrase: ${{ secrets.DIGITAL_OCEAN_PASSPHRASE }}
+          host: ${{ secrets.DIGITAL_IP4_ADDRESS }}  # Droplet IP address
+          username: root  # Root user (or appropriate user with Docker permissions)
+          key: cinepass-server  # Private key file created earlier
+          passphrase: ${{ secrets.DIGITAL_OCEAN_PASSPHRASE }}  # Optional if the private key requires a passphrase
           script: |
+
+            # Stop and remove the existing Docker container
             docker stop cinepass-server || true
             docker rm cinepass-server || true
+
+            # Remove the old Docker image
+            docker rmi arjunkan22/cinepass-server:latest || true
+
+            # Pull the latest Docker image from Docker Hub
             docker pull arjunkan22/cinepass-server:latest
+
+            # Run the container with the latest image
             docker run -d --name cinepass-server -p 3001:3001 --env-file .env arjunkan22/cinepass-server
 
+      # Cleanup the private key file
       - name: Cleanup Private Key
         run: rm cinepass-server
